# Site settings
title: Rhino Developer Docs
# email: alain@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "" # set by the build script

url: "http://developer.rhino3d.com" # the base hostname & protocol for your site
nwo: "mcneel/developer-rhino3d-com" # github repository (name with owner)
# twitter_username: ""
github_username:  mcneel

repository: mcneel/developer-rhino3d-com


# RhinoScriptSyntax API docs
rss_show_bad_docstring: true
rss_show_missing_examples_links: false

# site variables
rhino:
  windows_path: "C:\\Program Files\\Rhino 7"
  mac_path: "/Applications/Rhino 7.app"

# Build settings
#markdown: redcarpet

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
      disable: true
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

#port: 4444

timezone: "America/Los_Angeles"

safe: true

collections:
  - authors
  - faqs
  - guide_topics
  - guide_advanced_topics
  - api
  - glossary
  - cheat_sheet_items
  - samples
  - videos

collections:
  guide_topics:
    output: true
    permalink: /guides/:path/
  api:
    output: true
    permalink: /api/:path/
  samples:
    output: true
    permalink: /samples/:path/
  videos:
    output: true
    permalink: /videos/
  authors:
    output: true
    permalink: /authors/:path/

exclude: [script, test, README.md, CONTRIBUTING.md, Gemfile, vendor]

# version branches
versions:
  stable: "7"
  branches:
    - master # => wip
    - "5"
    - "6"
    - "7"
